name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -Pversion=1.0-SNAPSHOT
    - name: Unit Tests
      run: ./gradlew test
    - name: Publish Artifact
      run: ./gradlew publish -Pversion=1.0-SNAPSHOT
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
